# SonarQube project configuration — frontend-service
# Self-hosted SonarQube (no sonar.organization needed)
sonar.projectKey=shopnova-frontend-service
sonar.projectName=ShopNova Frontend Service
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.js,**/*.spec.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info
